Import('RTT_ROOT')
Import('rtconfig')
from building import *
groups = []
cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

groups += DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

groups += SConscript('LinkSDK/SConscript')

Return('groups')
